### ISSUE TITLE
Add links to technologies in info box

### ISSUE THREAD

**Issue by demodude4u** [demodude4u/Discord-Core-Bot-Apple#1]

**Comment by Nikey646** [comment]
This idea and concept was stolen from me and my bot, let it be known. [It was commited to my repo a grand 15min before this issue was even created!](https://gitlab.com/KuroThing/KuroBot/commit/99243dd9a8b8a555732e2b558c22fb13a7fcc687)

**Comment by demodude4u** [comment]
delet this

**Comment by demodude4u** [comment]
I came up with an ingenious idea to use link masking with the syntax `[Title](link)` for better readability

**Comment by Nikey646** [comment]
*claps*

He meant `[title](link)`

![Woops](https://u.nya.is/uxeuvn.png)

**Comment by demodude4u** [comment]
How about I just let people provide `[]()` syntax in the existing field values, no need for any special API...

**Comment by Nikey646** [comment]
That works as well, since the link is easily optional then.
